# -----------------------------------------------------------------------------
# Script Exporter
# -----------------------------------------------------------------------------
"""
Export simulation configurations as standalone Python scripts.

Generates executable Python code that reproduces the current
simulation setup without requiring the GUI.
"""

from pathlib import Path
from typing import Dict, Any, Optional, List
from datetime import datetime
import textwrap


class ScriptExporter:
    """
    Export simulation configurations as Python scripts.

    Generates standalone scripts that can reproduce the simulation
    setup using the underlying modules directly.
    """

    HEADER_TEMPLATE = '''\
#!/usr/bin/env python3
"""
X-ray Diffraction Simulation Script
Generated by X-ray Simulator GUI

Date: {date}
{description}
"""

import numpy as np
from pathlib import Path

# Import simulation modules
from Crystal import Crystal
from Sample import Sample
from Beam import Beam
from Detector import Detector
from Stage import Stage
from Optics import Optics
from Defects import Defects
from Deformation import Deformation
from Experiment import Experiment
from Analysis import Analysis

'''

    def __init__(self):
        """Initialize the script exporter."""
        pass

    def export_from_state(self, state, output_path: Path,
                          description: str = "",
                          include_simulation: bool = True) -> bool:
        """
        Export current simulation state as a Python script.

        Args:
            state: SimulationState instance
            output_path: Path to save the script
            description: Optional description for script header
            include_simulation: Whether to include simulation execution code

        Returns:
            True if export successful
        """
        try:
            lines = []

            # Header
            lines.append(self.HEADER_TEMPLATE.format(
                date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                description=f"Description: {description}" if description else ""
            ))

            # Crystal setup
            if state.crystal:
                lines.append(self._export_crystal(state.crystal))

            # Sample setup
            if state.sample:
                lines.append(self._export_sample(state.sample))

            # Beam setup
            if state.beam:
                lines.append(self._export_beam(state.beam))

            # Detector setup
            if state.detector:
                lines.append(self._export_detector(state.detector))

            # Stage setup
            if state.stage:
                lines.append(self._export_stage(state.stage))

            # Optics setup
            if state.optics:
                lines.append(self._export_optics(state.optics))

            # Defects setup
            if state.defects:
                lines.append(self._export_defects(state.defects))

            # Deformation setup
            if state.deformation:
                lines.append(self._export_deformation(state.deformation))

            # Simulation execution
            if include_simulation:
                lines.append(self._export_simulation_code(state))

            # Write to file
            script_content = "\n".join(lines)
            with open(output_path, 'w') as f:
                f.write(script_content)

            return True

        except Exception as e:
            print(f"Error exporting script: {e}")
            return False

    def export_from_preset(self, preset_data: Dict[str, Any], output_path: Path,
                           include_simulation: bool = True) -> bool:
        """
        Export a preset as a Python script.

        Args:
            preset_data: Preset data dict
            output_path: Path to save the script
            include_simulation: Whether to include simulation execution code

        Returns:
            True if export successful
        """
        try:
            params = preset_data.get("parameters", {})
            lines = []

            # Header
            lines.append(self.HEADER_TEMPLATE.format(
                date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                description=f"Preset: {preset_data.get('name', 'Unknown')}\n"
                           f"Description: {preset_data.get('description', '')}"
            ))

            # Crystal from preset
            if "crystal" in params:
                lines.append(self._export_crystal_from_params(params["crystal"]))

            # Sample from preset
            if "sample" in params:
                lines.append(self._export_sample_from_params(params["sample"]))

            # Beam from preset
            if "beam" in params:
                lines.append(self._export_beam_from_params(params["beam"]))

            # Detector from preset
            if "detector" in params:
                lines.append(self._export_detector_from_params(params["detector"]))

            # Stage from preset
            if "stage" in params:
                lines.append(self._export_stage_from_params(params["stage"]))

            # Simulation execution
            if include_simulation:
                lines.append(self._export_basic_simulation())

            # Write to file
            script_content = "\n".join(lines)
            with open(output_path, 'w') as f:
                f.write(script_content)

            return True

        except Exception as e:
            print(f"Error exporting preset script: {e}")
            return False

    def _export_crystal(self, crystal) -> str:
        """Export Crystal setup code."""
        lines = ["# Crystal Setup", "# " + "-" * 60]

        # Check if loaded from CIF
        if hasattr(crystal, 'cif_path') and crystal.cif_path:
            lines.append(f'crystal = Crystal("{crystal.cif_path}")')
        else:
            # Manual construction
            lines.append("crystal = Crystal()")
            if hasattr(crystal, 'a'):
                lines.append(f"crystal.a = {crystal.a}")
            if hasattr(crystal, 'b'):
                lines.append(f"crystal.b = {crystal.b}")
            if hasattr(crystal, 'c'):
                lines.append(f"crystal.c = {crystal.c}")
            if hasattr(crystal, 'alpha'):
                lines.append(f"crystal.alpha = {crystal.alpha}")
            if hasattr(crystal, 'beta'):
                lines.append(f"crystal.beta = {crystal.beta}")
            if hasattr(crystal, 'gamma'):
                lines.append(f"crystal.gamma = {crystal.gamma}")

        # Orientation
        if hasattr(crystal, 'hkl_primary') and crystal.hkl_primary is not None:
            lines.append(f"crystal.set_orientation({list(crystal.hkl_primary)}, {list(crystal.hkl_secondary)})")

        lines.append("")
        return "\n".join(lines)

    def _export_crystal_from_params(self, params: Dict[str, Any]) -> str:
        """Export Crystal setup from preset params."""
        lines = ["# Crystal Setup", "# " + "-" * 60]

        if "cif_file" in params:
            lines.append(f'crystal = Crystal("{params["cif_file"]}")')
        else:
            lines.append("crystal = Crystal()")
            lp = params.get("lattice_parameters", {})
            for key in ["a", "b", "c", "alpha", "beta", "gamma"]:
                if key in lp and lp[key] is not None:
                    lines.append(f"crystal.{key} = {lp[key]}")

        lines.append("")
        return "\n".join(lines)

    def _export_sample(self, sample) -> str:
        """Export Sample setup code."""
        lines = ["# Sample Setup", "# " + "-" * 60]

        # Dimensions
        Lx = getattr(sample, 'Lx', 10000)
        Ly = getattr(sample, 'Ly', 10000)
        Lz = getattr(sample, 'Lz', 10000)

        lines.append(f"sample = Sample(crystal, Lx={Lx}, Ly={Ly}, Lz={Lz})")

        # Temperature if enabled
        if hasattr(sample, 'temperature_enabled') and sample.temperature_enabled:
            lines.append(f"sample.enable_temperature({getattr(sample, 'temperature', 300)})")

        lines.append("sample.generate()")
        lines.append("")
        return "\n".join(lines)

    def _export_sample_from_params(self, params: Dict[str, Any]) -> str:
        """Export Sample setup from preset params."""
        lines = ["# Sample Setup", "# " + "-" * 60]

        dims = params.get("dimensions", {})
        Lx = dims.get("Lx", 10000)
        Ly = dims.get("Ly", 10000)
        Lz = dims.get("Lz", 10000)

        lines.append(f"sample = Sample(crystal, Lx={Lx}, Ly={Ly}, Lz={Lz})")
        lines.append("sample.generate()")
        lines.append("")
        return "\n".join(lines)

    def _export_beam(self, beam) -> str:
        """Export Beam setup code."""
        lines = ["# Beam Setup", "# " + "-" * 60]

        energy = getattr(beam, 'energy', 17000)
        shape = getattr(beam, 'shape', 'rectangular')

        lines.append(f"beam = Beam(sample, energy={energy})")
        lines.append(f'beam.shape = "{shape}"')

        # Size parameters
        for attr in ['Ny', 'Nz', 'Ly', 'Lz']:
            if hasattr(beam, attr):
                lines.append(f"beam.{attr} = {getattr(beam, attr)}")

        # Profile
        if hasattr(beam, 'profile'):
            lines.append(f'beam.profile = "{beam.profile}"')
            if beam.profile == 'gaussian':
                if hasattr(beam, 'waist_y'):
                    lines.append(f"beam.waist_y = {beam.waist_y}")
                if hasattr(beam, 'waist_z'):
                    lines.append(f"beam.waist_z = {beam.waist_z}")

        # Polarization
        if hasattr(beam, 'polarization_rate'):
            lines.append(f"beam.polarization_rate = {beam.polarization_rate}")

        lines.append("")
        return "\n".join(lines)

    def _export_beam_from_params(self, params: Dict[str, Any]) -> str:
        """Export Beam setup from preset params."""
        lines = ["# Beam Setup", "# " + "-" * 60]

        energy = params.get("energy", 17000)
        lines.append(f"beam = Beam(sample, energy={energy})")

        for key in ["shape", "Ny", "Nz", "Ly", "Lz", "profile", "polarization_rate"]:
            if key in params and params[key] is not None:
                val = params[key]
                if isinstance(val, str):
                    lines.append(f'beam.{key} = "{val}"')
                else:
                    lines.append(f"beam.{key} = {val}")

        lines.append("")
        return "\n".join(lines)

    def _export_detector(self, detector) -> str:
        """Export Detector setup code."""
        lines = ["# Detector Setup", "# " + "-" * 60]

        lines.append("from Detector import detector")
        lines.append("detector_obj = detector(directory='./detector_data')")
        lines.append("")

        # Export create_detector call
        if hasattr(detector, 'shape') and detector.shape is not None:
            shape = detector.shape
            pixel_size = getattr(detector, 'pixel_size', (100, 100))
            geometry = getattr(detector, '_geometry', 'rectangular')
            construction_mode = getattr(detector, '_construction_mode', 'plane')
            input_mode = getattr(detector, '_input_mode', 'spatial')
            angular_range = getattr(detector, '_angular_range', None)

            # For angular mode, use the original angular range as shape
            if input_mode == 'angular' and angular_range is not None:
                shape_str = f"({', '.join(str(x) for x in angular_range)})"
            else:
                shape_str = f"({shape[0]}, {shape[1]})"

            lines.append("detector_obj.create_detector(")
            lines.append(f"    shape={shape_str},")
            lines.append(f"    pixel_size=({pixel_size[0]}, {pixel_size[1]}),")
            lines.append(f"    geometry='{geometry}',")
            lines.append(f"    construction_mode='{construction_mode}',")
            lines.append(f"    input_mode='{input_mode}'")
            lines.append(")")
            lines.append("")

        # Export position_detector_absolute call
        if hasattr(detector, 'distance') and detector.distance is not None:
            distance = detector.distance
            two_theta = getattr(detector, 'two_theta', 0)
            eta = getattr(detector, 'eta', 0)

            # Convert radians to degrees for export
            import numpy as np
            two_theta_deg = float(np.degrees(two_theta))
            eta_deg = float(np.degrees(eta))

            lines.append("detector_obj.position_detector_absolute(")
            lines.append(f"    distance={distance},")
            lines.append(f"    two_theta={two_theta_deg:.4f},")
            lines.append(f"    eta={eta_deg:.4f},")
            lines.append("    degrees=True")
            lines.append(")")

        lines.append("")
        return "\n".join(lines)

    def _export_detector_from_params(self, params: Dict[str, Any]) -> str:
        """Export Detector setup from preset params."""
        lines = ["# Detector Setup", "# " + "-" * 60]

        lines.append("from Detector import detector")
        lines.append("detector_obj = detector(directory='./detector_data')")
        lines.append("")

        # Export create_detector call
        shape = params.get('shape', [256, 256])
        pixel_size = params.get('pixel_size', [100, 100])
        geometry = params.get('geometry', 'rectangular')
        construction_mode = params.get('construction_mode', 'plane')
        input_mode = params.get('input_mode', 'spatial')
        angular_range = params.get('angular_range')

        # For angular mode, use angular_range as shape if available
        if input_mode == 'angular' and angular_range is not None:
            shape_str = f"({', '.join(str(x) for x in angular_range)})"
        else:
            shape_str = f"({shape[0]}, {shape[1]})"

        lines.append("detector_obj.create_detector(")
        lines.append(f"    shape={shape_str},")
        lines.append(f"    pixel_size=({pixel_size[0]}, {pixel_size[1]}),")
        lines.append(f"    geometry='{geometry}',")
        lines.append(f"    construction_mode='{construction_mode}',")
        lines.append(f"    input_mode='{input_mode}'")
        lines.append(")")
        lines.append("")

        # Export position_detector_absolute call
        if 'distance' in params:
            distance = params.get('distance', 1000)
            two_theta = params.get('two_theta', 0)
            eta = params.get('eta', 0)

            lines.append("detector_obj.position_detector_absolute(")
            lines.append(f"    distance={distance},")
            lines.append(f"    two_theta={two_theta:.4f},")
            lines.append(f"    eta={eta:.4f},")
            lines.append("    degrees=True")
            lines.append(")")

        lines.append("")
        return "\n".join(lines)

    def _export_stage(self, stage) -> str:
        """Export Stage setup code."""
        lines = ["# Stage Setup", "# " + "-" * 60]

        lines.append("stage = Stage(sample)")

        if hasattr(stage, 'motors'):
            for name, motor in stage.motors.items():
                val = getattr(motor, 'value', 0)
                if val != 0:
                    lines.append(f'stage.set_motor("{name}", {val})')

        lines.append("")
        return "\n".join(lines)

    def _export_stage_from_params(self, params: Dict[str, Any]) -> str:
        """Export Stage setup from preset params."""
        lines = ["# Stage Setup", "# " + "-" * 60]

        lines.append("stage = Stage(sample)")

        motors = params.get("motors", {})
        for name, value in motors.items():
            if value != 0:
                lines.append(f'stage.set_motor("{name}", {value})')

        lines.append("")
        return "\n".join(lines)

    def _export_optics(self, optics) -> str:
        """Export Optics setup code."""
        lines = ["# Optics Setup", "# " + "-" * 60]

        lines.append("optics = Optics()")

        # Export component stack if available
        if hasattr(optics, 'components'):
            for comp in optics.components:
                comp_type = type(comp).__name__
                lines.append(f"# optics.add_{comp_type.lower()}(...)")

        lines.append("")
        return "\n".join(lines)

    def _export_defects(self, defects) -> str:
        """Export Defects setup code."""
        lines = ["# Defects Setup", "# " + "-" * 60]

        lines.append("defects = Defects(sample)")
        lines.append("# Configure defects as needed")

        lines.append("")
        return "\n".join(lines)

    def _export_deformation(self, deformation) -> str:
        """Export Deformation setup code."""
        lines = ["# Deformation Setup", "# " + "-" * 60]

        lines.append("deformation = Deformation(sample)")

        if hasattr(deformation, 'field_path') and deformation.field_path:
            lines.append(f'deformation.load_field("{deformation.field_path}")')

        lines.append("")
        return "\n".join(lines)

    def _export_simulation_code(self, state) -> str:
        """Export simulation execution code."""
        lines = [
            "# Simulation Execution",
            "# " + "-" * 60,
            "",
            "# Run simulation",
            "beam.atomic_direct_interaction()",
            "",
            "# Display results",
            "detector.plot()",
            "",
            'print("Simulation complete!")',
        ]
        return "\n".join(lines)

    def _export_basic_simulation(self) -> str:
        """Export basic simulation execution code."""
        lines = [
            "# Simulation Execution",
            "# " + "-" * 60,
            "",
            "# Run simulation",
            "beam.atomic_direct_interaction()",
            "",
            "# Display results",
            "detector.plot()",
            "",
            'print("Simulation complete!")',
        ]
        return "\n".join(lines)

    def generate_scan_script(self, state, scan_config) -> str:
        """
        Generate a script for running an nD scan.

        Args:
            state: SimulationState instance
            scan_config: ScanConfig with scan parameters

        Returns:
            Python script as string
        """
        lines = []

        # Header
        lines.append(self.HEADER_TEMPLATE.format(
            date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            description="nD Scan Script"
        ))

        # Setup code (abbreviated)
        lines.append("# Setup simulation objects")
        lines.append("# ... (configure crystal, sample, beam, detector as needed)")
        lines.append("")

        # Experiment setup
        lines.append("# Experiment/Scan Setup")
        lines.append("# " + "-" * 60)
        lines.append("experiment = Experiment(beam, detector, stage)")
        lines.append("")

        # Scan parameters
        motors = scan_config.motors
        ranges = scan_config.ranges
        steps = scan_config.steps

        lines.append("# Define scan parameters")
        lines.append(f"motors = {motors}")
        lines.append(f"ranges = {ranges}")
        lines.append(f"steps = {steps}")
        lines.append("")

        # Execute scan
        lines.append("# Run scan")
        lines.append("results = experiment.scan_nD(")
        lines.append("    motors=motors,")
        lines.append("    ranges=ranges,")
        lines.append("    steps=steps,")
        lines.append(f'    output_dir="{scan_config.output_directory or "scan_output"}"')
        lines.append(")")
        lines.append("")
        lines.append('print("Scan complete!")')

        return "\n".join(lines)
